### ISSUE TITLE
Is it support other props when I want to download bpmn or trigger click event?

### ISSUE THREAD

**Issue by jenniferxu2454** [bpmn-io/react-bpmn#5]
Is it support other props if I want to download bpmn OR trigger click event OR add one comment?
is it only have below props?

-       url="/public/diagram.bpmn"
-       onShown={ onShown }
-       onLoading={ onLoading }
-       onError={ onError }

Because My project want use BPMN and it is a React project..
Thanks so much.....

**Comment by pinussilvestrus** [comment]
Currently, it has only these props. But as any other react project, it shouldn't keep you away from adding another functionality. This project offers a minimal starting point rendering BPMN inside a react component. You can do whatever you want on top of it.

I'll close this since no real bug report or feature request is described. Please use [our forum](https://forum.bpmn.io/) in the future to ask questions like this. GitHub issues are more intended for Bug reports and feature requests.
